#%RAML 1.0
title: Process API for Products.
description: This API serves as orchestration for processing Products.
version: v1

/v1: 
  /products:
    /new:
      post:
        responses:
          201:
      